#baseURL = "https://snipdome.github.io/"
languageCode = "en"
title = "Domenico's web-corner"
theme = ["hugo-initio"]
# uglyURLs = true
# relativeURLs = true

# [build.environment]
#   HUGO_ENV = "production"
#   HUGO_VERSION = "0.134.1"

[params]
    name = "Domenico Iuso, PhD"
    description = "Understanding X-rays with a discrete (A)I"
    email = "snipdomenico@gmail.com"
    #phone = "+234 23 9873237"
    #address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2024
    avatar = "images/photo.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/bg_head.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "September 13, 2024"
    author = "Domenico Iuso"

    showSubheader = true
    showServices = false
    showRecentWorks = true
    showDownloads = false
    showTools = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

#[[params.social]]
#	title = "facebook"
#	url = "https://www.facebook.com/nickname"
#    icon = "fab fa-facebook-square"
#    footer = true
#    sharethis = true
#    network = "facebook"
#[[params.social]]
#	title = "twitter"
#	url = "https://twitter.com/nickname"
#    icon = "fab fa-twitter-square"
#    footer = true
#    sharethis = true
#    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/snipdome"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
#[[params.social]]
#	title = "google+"
#	url = "https://plus.google.com/+nickname"
#    icon = "fab fa-google-plus-square"
#    footer = false
#    sharethis = true
#    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/domenicoiuso/"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
# [[params.social]]
# 	title = "tumblr"
# 	url = "https://nickname.tumblr.com"
#     icon = "fab fa-tumblr-square"
#     footer = false
#     sharethis = false
#     network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/snipdome"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:snipdomenico@gmail.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
